### ISSUE TITLE
make user without login to create button and then request to login/signup

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/hb-front#155]
The idea is that no logged can complete the form and be asked to login at the end, to create, then the route will flow to Explore with the button created

**Comment by albjeremias** [comment]
TODO:
 - tag fields is not recovered

I'm storing the formdata from the buttonNew in the local storage, but i get this error
 - image fields exceed the quota of the localStorage, maybe the approeach should be to store the button as not-published?! or simply don't store any images?!
@watchoutfreedom what do you think?

**Comment by watchoutfreedom** [comment]
Yes, I think the proper approach would be to store it as not published. In the old version, we could activate/deactivate buttons to be shown/hidden , maybe we can recover this property for this type of cases and maybe reuse in other cases (it may be useful for other cases)
