### ISSUE TITLE
Implement React components and elements to work with variables

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/hb-front#23]
I would start taking Btn component in elements folder and make a class with "hasIcon", "caption" etc variables.  so it can be inserted in other components with an <Btn /> tag and doesn't need to be reposted everywhere. 

Then I would the same with the rest of elements folder.

**Comment by dukebody** [comment]
Me pongo con esto.

**Comment by watchoutfreedom** [comment]
This was perfect. I don't know if we can continue with more elements but in general it's great.

**Comment by watchoutfreedom** [comment]
@iiaan maybe you can also continue this issue.
