### ISSUE TITLE
Enable file upload in ButtonNew page

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/hb-front#44]
1 . Unify styles in the add image button so it works as an upload file button. 
2. Integrate a provisional image URL for the preview and sent into the api call received by the CreateButtonEvent and ButtonService
<img width="957" alt="Captura de pantalla 2021-10-10 a las 11 12 57" src="https://user-images.githubusercontent.com/23015314/136689723-42a9cbd1-f499-4e2c-bac6-65f5a1dee35e.png">

**Comment by watchoutfreedom** [comment]
yes!

**Comment by mtwn105** [comment]
Hi I did fix the first part. I am not understanding the 2nd one can you explain?

**Comment by watchoutfreedom** [comment]
> Hi I did fix the first part. I am not understanding the 2nd one can you explain?

Yes, we need a small preview of the images once we add them. So there will be an image array below the add button where you can see / remove images. Aesthetically is open to your proposal, we can work on it later. thanks
