### ISSUE TITLE
Implement Geosearch

### ISSUE THREAD

**Issue by watchoutfreedom** [helpbuttons/hb-front#75]
Implement Geosearch in the Home and Explore pages  following this example or similar. 

https://stackoverflow.com/questions/48290555/react-leaflet-search-box-implementation

**Comment by watchoutfreedom** [comment]
Already working on it , buttons/find is already implemented in map and list components

**Comment by watchoutfreedom** [comment]
Pending to make search field in HomeInfo page to redirect to Explore page with the map location that was selected. 
<img width="1009" alt="Captura de pantalla 2022-04-16 a las 15 01 35" src="https://user-images.githubusercontent.com/23015314/163676101-1bd0d858-905b-4ad8-bd0b-63b27e5969ab.png">

**Comment by albjeremias** [comment]
```
Unacceptable Use

The following uses are strictly forbidden and will get you banned:

    **Auto-complete search This is not yet supported by Nominatim and you must not implement such a service on the client side using the API.**
    Systematic queries This includes reverse queries in a grid, searching for complete lists of postcodes, towns etc. and downloading all POIs in an area. If you need complete sets of data, get it from the [OSM planet](https://planet.openstreetmap.org/) or an extract.
    Scraping of details The details page is there for debugging only and may not be downloaded automatically.
```
https://operations.osmfoundation.org/policies/nominatim/

**Comment by albjeremias** [comment]
@watchoutfreedom i will use this one for now.. it also has routes calculation:
https://apidocs.geoapify.com/#playgrounds
