### ISSUE TITLE
finishing up signup

### ISSUE THREAD

**Issue by albjeremias** [helpbuttons/hb-front#87]
1 - Would be cool to show at least an alert explaining the user that the signup went good.. and only after maybe do a route push?
2 - The backend  needs to validate the number of caracteres for the password, because after it won't let the user login with a password with less than 7 characters

[1] - 
alerts won't show after router.push
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
Alert@webpack-internal:///./src/components/overlay/Alert/index.tsx:47:12
div
div
Popup@webpack-internal:///./src/components/popup/Popup/index.tsx:18:18
PopupSignup@webpack-internal:///./src/components/user/PopupSignup/index.tsx:54:70
Signup react-dom.development.js:67
```

https://github.com/helpbuttons/hb-front/blob/develop/src/pages/Signup/data.tsx#L24

**Comment by watchoutfreedom** [comment]
Will check this. The alertservice can shw the errors and Maybe we can include the alert in the home and check if the wiindow token was updated, then perform an success alert.

**Comment by iiaan** [comment]
For the notification we can use Chakra's Toast it looks very nice [](https://imgur.com/5bORr0D)

**Comment by watchoutfreedom** [comment]
> For the notification we can use Chakra's Toast it looks very nice https://imgur.com/5bORr0D

We allready have an alert system that we can adapt. The problem here is how to implement the alert before the page changes so it gives time to the user to see the message.
