### ISSUE TITLE
perf: Fuga de memoria en observables

### ISSUE THREAD

**Issue by dbrab** [helpbuttons/hb-front#89]
Hola , me parece que tienen algunos problemas de fuga de memoria en los observables.
[https://github.com/helpbuttons/hb-front/blob/develop/src/pages/Explore/data.tsx](url)
[https://github.com/helpbuttons/hb-front/blob/develop/src/pages/Explore/index.tsx](url)
[https://github.com/helpbuttons/hb-front/blob/develop/src/pages/HomeInfo/data.tsx](url)
[https://github.com/helpbuttons/hb-front/blob/develop/src/pages/HomeInfo/index.tsx](url)
Específicamente en la parte donde usan los hooks

 ```
 useEffect(() => {

    GetNetworksEvent(setNetworks);
    GetNetworkByIdEvent(selectedNetwork, setSelectedNetworkObject);

  }, [])
```

Aqui en ningún momento se vuelve la llamada para desuscribirse, un simple return arreglaria todo o en su defecto hacer un custom hook que se desuscriba algo como esto

`const useUnsubscribe=(sub)=>useEffect(()=>sub,[]);`

Hice un ejemplo con retornando y no retornando el callback de la funcion que limpia 

[ejemplo](https://stackblitz.com/edit/react-g3v326?file=src/App.js)

En el ejemplo tengo 2 componentes uno con retorno y otro sin retorno , ambos usan observables y la data se envía a través de un subject dandole click en fired data. Cuando envías data y destruyes el componente que no tiene el return , verán que el observable sigue recibiendo data pues no se llamo a la función que limpia en ningún momento , esto puede tener efectos extraños aparte de la fuga de memoria , como partes que no se sincronizan , en caso el subject este en algún nivel del árbol de la vista actual , entre otros.
En el segundo componente con return , cuando se destruye el componente , y sigue enviándose datos , verán que el observable de este componente ya no recibe datos , pues se limpio correctamente.

**Comment by watchoutfreedom** [comment]
Si esto es algo que tenía pendiente , te diré la opción de que veo mejor. No sé si @hirunatan puede aportar algo aquí que sabe más de esto.
