### ISSUE TITLE
Sugerencia

### ISSUE THREAD

**Issue by dbrab** [helpbuttons/hb-front#90]
Sugiero usar commits convencionales para estandarizar el trabajo , si bien es cierto no es necesario ser purista y hacer un commit por cada movimiento , creo que ayudaría a tener algo mas normalizado en la gestión, a la vés que muchos generadores de versiones actuales usan este standard para poder generar automáticamente las versiones en lanzamiento , así como configurar el repo con husky , commilint , para evitar la mala praxis de la misma.
[Conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
[standard version , generar changelogs automaticos o manuales](https://www.npmjs.com/package/standard-version?activeTab=versions)
[Commilint](https://github.com/conventional-changelog/commitlint)

Hare un pull request con estas adiciones en ambos repos , apenas me desocupe.

**Comment by watchoutfreedom** [comment]
ok perfecto, hazla y la comentamos @albjeremias también tendrá su opinión
